/**
 * Fish Species Database Seeding Script
 * 鱼类百科数据库初始化脚本
 * 
 * Usage: npx ts-node scripts/seed-fish-species.ts
 */

import { DataSource } from 'typeorm';
import { FishSpecies, ProtectionLevelEnum } from '../src/entities/fish-species.entity';

const dataSource = new DataSource({
  type: 'postgres',
  host: process.env.DB_HOST || 'localhost',
  port: parseInt(process.env.DB_PORT || '5432'),
  username: process.env.DB_USERNAME || 'postgres',
  password: process.env.DB_PASSWORD || 'postgres',
  database: process.env.DB_DATABASE || 'yediao',
  entities: [FishSpecies],
  synchronize: false,
});

const FISH_SPECIES_DATA = [
  {
    chineseName: '鲫鱼',
    scientificName: 'Carassius auratus',
    family: '鲤科',
    genus: '鲫属',
    aliases: ['鲫瓜子', '草鱼板', '河鲫'],
    habitat: '底层鱼类，喜栖息于水草丰富的静水或缓流区域，适应性强，全国各地均有分布',
    diet: '杂食性，主要以植物性饵料为主，也吃水生昆虫、浮游动物',
    waterLayer: '底层',
    bestSeason: '春季（3-5月）和秋季（9-11月）',
    protectionLevel: ProtectionLevelEnum.NONE,
    iucnStatus: 'LC',
    edibleRating: '肉质细嫩，味道鲜美，适合红烧、炖汤',
    cookingMethods: ['红烧', '炖汤', '清蒸', '糖醋'],
    contraindications: '痛风患者慎食',
    baitRecommendation: '蚯蚓、红虫、商品饵（腥香篇）',
    rigSuggestion: '台钓钓底，草窝钓法，鱼钩3-5号袖钩',
    tips: '鲫鱼警惕性高，抛竿要轻，饵料状态比味型更重要',
    similarSpecies: ['鲤鱼', '小金线鱼'],
    modelLabelId: 1,
  },
  {
    chineseName: '鲤鱼',
    scientificName: 'Cyprinus carpio',
    family: '鲤科',
    genus: '鲤属',
    aliases: ['拐子', '红鱼', '鲤拐子'],
    habitat: '底层鱼类，适应性强，喜弱碱性水质，多栖息于静水或缓流区域',
    diet: '杂食性，螺蛳、贝类、水草、昆虫均食',
    waterLayer: '底层',
    bestSeason: '春季和秋季，夏季早晚也是好时机',
    protectionLevel: ProtectionLevelEnum.NONE,
    iucnStatus: 'LC',
    edibleRating: '肉质紧实，味道浓郁，适合红烧和炖汤',
    cookingMethods: ['红烧', '糖醋', '炖汤', '烧烤'],
    contraindications: '过敏体质者慎食',
    baitRecommendation: '玉米粒、螺蛳、红薯、商品饵（薯香篇）',
    rigSuggestion: '滑铅钓法，玉米粒钓，活螺蛳挂钩，子线30cm以上',
    tips: '鲤鱼喜甜香，添加蜂蜜或红糖效果更好',
    similarSpecies: ['鲫鱼', '草鱼'],
    modelLabelId: 2,
  },
  {
    chineseName: '草鱼',
    scientificName: 'Ctenopharyngodon idella',
    family: '鲤科',
    genus: '草鱼属',
    aliases: ['草混子', '草鱼根', '鲩鱼'],
    habitat: '中下层鱼类，喜游弋于水草丰茂的区域，生长迅速，国内各大水系均有分布',
    diet: '草食性，以水草、陆生嫩叶为主，也吃昆虫和粮食饵料',
    waterLayer: '中下层',
    bestSeason: '夏季和初秋（6-9月）',
    protectionLevel: ProtectionLevelEnum.NONE,
    iucnStatus: 'LC',
    edibleRating: '肉质白嫩，刺少，适合多种烹饪方式',
    cookingMethods: ['水煮鱼', '酸菜鱼', '清蒸', '烧烤'],
    contraindications: '无特殊禁忌',
    baitRecommendation: '嫩草、玉米叶、芦苇心、商品饵（草鱼篇）',
    rigSuggestion: '浮钓钓离底，钓浮打频率，玉米粒或草饵',
    tips: '草鱼怕热，夏天中午难钓，傍晚和夜间是黄金时段',
    similarSpecies: ['青鱼', '鳊鱼'],
    modelLabelId: 3,
  },
  {
    chineseName: '青鱼',
    scientificName: 'Mylopharyngodon piceus',
    family: '鲤科',
    genus: '青鱼属',
    aliases: ['青混子', '螺丝青', '乌青'],
    habitat: '底层鱼类，肉食性，喜食螺蛳和贝类，多栖息于深水区域',
    diet: '肉食性，主食螺蛳、蚌类，也吃小鱼和水生昆虫',
    waterLayer: '底层',
    bestSeason: '秋季（9-11月）',
    protectionLevel: ProtectionLevelEnum.NONE,
    iucnStatus: 'VU',
    edibleRating: '肉质鲜美，刺少，被称为\"淡水石斑\"',
    cookingMethods: ['清蒸', '红烧', '煮汤', '刺身'],
    contraindications: '过敏体质者慎食',
    baitRecommendation: '螺蛳、蚌肉、玉米粒、商品饵（螺蛳篇）',
    rigSuggestion: '螺蛳打窝，钓底，线组要粗，钩子用伊势尼10号以上',
    tips: '青鱼力道大，中鱼后要做好溜鱼准备',
    similarSpecies: ['草鱼', '鳜鱼'],
    modelLabelId: 4,
  },
  {
    chineseName: '鲢鱼',
    scientificName: 'Hypophthalmichthys molitrix',
    family: '鲤科',
    genus: '鲢属',
    aliases: ['白鲢', '跳鲢', '鲢子'],
    habitat: '上层鱼类，滤食性，喜集群，主要以浮游植物为食，有净化水质的作用',
    diet: '滤食性，以浮游植物为主，兼食浮游动物',
    waterLayer: '上层',
    bestSeason: '夏季（6-8月）',
    protectionLevel: ProtectionLevelEnum.NONE,
    iucnStatus: 'LC',
    edibleRating: '肉质细嫩，刺多，适合红烧或腌制',
    cookingMethods: ['红烧', '干烧', '腌制'],
    contraindications: '刺多，老人和儿童食用需谨慎',
    baitRecommendation: '轻麸、雪花粉、商品饵（鲢鳙篇）',
    rigSuggestion: '钓浮，水皮30-50cm，饵料要雾化好，钩距加大',
    tips: '鲢鱼喜酸臭，添加白醋和臭鸡蛋效果显著',
    similarSpecies: ['鳙鱼'],
    modelLabelId: 5,
  },
  {
    chineseName: '鳙鱼',
    scientificName: 'Aristichthys nobilis',
    family: '鲤科',
    genus: '鳙属',
    aliases: ['花鲢', '胖头鱼', '大头鱼'],
    habitat: '中上层鱼类，喜栖息于水质肥沃的水域，滤食浮游动物',
    diet: '滤食性，以浮游动物为主，也吃人工饵料',
    waterLayer: '中上层',
    bestSeason: '夏秋季（6-11月）',
    protectionLevel: ProtectionLevelEnum.NONE,
    iucnStatus: 'LC',
    edibleRating: '头部富含胶原蛋白，鱼肉细嫩，适合剁椒鱼头',
    cookingMethods: ['剁椒鱼头', '砂锅鱼头', '鱼丸'],
    contraindications: '鱼胆有毒，不可食用',
    baitRecommendation: '商品饵（鲢鳙篇）、红虫、浮游动物',
    rigSuggestion: '钓中层，饵料雾化要好，钩距8-10cm',
    tips: '鳙鱼嘴大，漂相清晰，容易抓口',
    similarSpecies: ['鲢鱼'],
    modelLabelId: 6,
  },
  {
    chineseName: '鳜鱼',
    scientificName: 'Siniperca chuatsi',
    family: '鮨科',
    genus: '鳜属',
    aliases: ['桂鱼', '季花鱼', '花脊鱼'],
    habitat: '底层肉食性鱼类，喜欢栖息于水流缓慢的溪流、水库和湖泊，常藏身于乱石和水草间',
    diet: '肉食性，主食小鱼、小虾，也吃泥鳅和昆虫',
    waterLayer: '底层',
    bestSeason: '春季（4-6月）和秋季（9-10月）',
    protectionLevel: ProtectionLevelEnum.NONE,
    iucnStatus: 'LC',
    edibleRating: '肉质细嫩，刺少，味道极其鲜美，被称为\"淡水鲈鱼\"',
    cookingMethods: ['清蒸', '红烧', '刺身', '松鼠鳜鱼'],
    contraindications: '过敏体质者慎食',
    baitRecommendation: '活泥鳅、小鱼、白饵、假饵（路亚）',
    rigSuggestion: '泥鳅打窝，活饵钓底，路亚跳底',
    tips: '鳜鱼攻击性强，路亚效果很好，亮片和米诺是常用假饵',
    similarSpecies: ['鲈鱼', '石斑鱼'],
    modelLabelId: 7,
  },
  {
    chineseName: '鲈鱼',
    scientificName: 'Lateolabrax japonicus',
    family: '鮨科',
    genus: '花鲈属',
    aliases: ['七星鲈', '海鲈'],
    habitat: '广盐性鱼类，淡水、海水均能生活，多栖息于近海河口和淡水水域',
    diet: '肉食性，主食小鱼、虾、蟹',
    waterLayer: '中下层',
    bestSeason: '秋季至初冬（10-12月）',
    protectionLevel: ProtectionLevelEnum.NONE,
    iucnStatus: 'LC',
    edibleRating: '肉质洁白，细嫩鲜美，刺少，是高档淡水鱼',
    cookingMethods: ['清蒸', '红烧', '刺身', '烤鱼'],
    contraindications: '无特殊禁忌',
    baitRecommendation: '活鱼、小虾、路亚假饵（米诺、铅笔）',
    rigSuggestion: '路亚为主，铅头钩配卷尾蛆，米诺搜索水层',
    tips: '鲈鱼对温度敏感，水温15-25度是最活跃期',
    similarSpecies: ['鳜鱼', '石斑鱼'],
    modelLabelId: 8,
  },
  {
    chineseName: '黑鱼',
    scientificName: 'Channa argus',
    family: '鳢科',
    genus: '鳢属',
    aliases: ['乌鳢', '财鱼', '蛇鱼'],
    habitat: '底层鱼类，适应性强，能在缺氧环境中生存，常见于水草丰富的池塘和沟渠',
    diet: '肉食性，主食小鱼、虾、青蛙，捕食凶猛',
    waterLayer: '底层',
    bestSeason: '夏季（5-9月）',
    protectionLevel: ProtectionLevelEnum.NONE,
    iucnStatus: 'LC',
    edibleRating: '肉质紧实，刺少，味道鲜美，有滋补效果',
    cookingMethods: ['水煮鱼', '酸菜鱼', '炒鱼片', '炖汤'],
    contraindications: '鱼皮粘液可能引起过敏',
    baitRecommendation: '活泥鳅、小鱼、青蛙、路亚假饵',
    rigSuggestion: '路亚优先，米诺和铅头钩最常用，搜索水草边缘',
    tips: '黑鱼护巢，繁殖期（5-6月）在水草区容易钓到',
    similarSpecies: ['斑鳢', '七星鱼'],
    modelLabelId: 9,
  },
  {
    chineseName: '黄鳝',
    scientificName: 'Monopterus albus',
    family: '合鳃鱼科',
    genus: '黄鳝属',
    aliases: ['鳝鱼', '长鱼', '血鳝'],
    habitat: '底层穴居鱼类，喜栖息于稻田、池塘、沟渠的泥沙中，昼伏夜出',
    diet: '肉食性，主食蚯蚓、小鱼、虾、昆虫',
    waterLayer: '底层穴居',
    bestSeason: '夏季（5-9月），夜间是最佳时段',
    protectionLevel: ProtectionLevelEnum.NONE,
    iucnStatus: 'LC',
    edibleRating: '肉质细嫩，刺少，味道鲜美，有补血功效',
    cookingMethods: ['响油鳝丝', '红烧', '爆炒', '鳝筒煲'],
    contraindications: '无特殊禁忌，寄生虫需确保完全熟食',
    baitRecommendation: '蚯蚓、小虾、动物肝脏',
    rigSuggestion: '长鱼钩钓法，星漂线组，夜间守钓',
    tips: '黄鳝力气大但嘴小，刺穿要轻不要猛提竿',
    similarSpecies: ['泥鳅', '鳗鱼'],
    modelLabelId: 10,
  },
  {
    chineseName: '泥鳅',
    scientificName: 'Misgurnus anguillicaudatus',
    family: '鳅科',
    genus: '泥鳅属',
    aliases: ['泥鳅鱼', '鱼鳅'],
    habitat: '底层鱼类，适应性强，能在缺氧的水中生存，栖息于稻田、池塘、沟渠的淤泥里',
    diet: '杂食性，水生昆虫、藻类、有机碎屑均食',
    waterLayer: '底层',
    bestSeason: '春末至秋季（4-10月）',
    protectionLevel: ProtectionLevelEnum.NONE,
    iucnStatus: 'LC',
    edibleRating: '肉质细嫩，营养丰富，被称为\"水中人参\"',
    cookingMethods: ['干煸', '红烧', '炖汤', '炸酥'],
    contraindications: '过敏体质者慎食',
    baitRecommendation: '蚯蚓、红虫、商品饵（腥香篇）',
    rigSuggestion: '星漂钓底，饵料轻拉，逗钓效果好',
    tips: '泥鳅是万能饵，钓肉食性鱼类的首选',
    similarSpecies: ['黄鳝', '刀鳅'],
    modelLabelId: 11,
  },
  {
    chineseName: '鳊鱼',
    scientificName: 'Parabramis pekinensis',
    family: '鲤科',
    genus: '鳊属',
    aliases: ['长春鳊', '草鳊'],
    habitat: '中下层鱼类，喜栖息于水草丰茂的静水或缓流区域，分布广泛',
    diet: '草食性为主，也吃水生昆虫和藻类',
    waterLayer: '中下层',
    bestSeason: '春季和秋季',
    protectionLevel: ProtectionLevelEnum.NONE,
    iucnStatus: 'LC',
    edibleRating: '肉质细嫩，刺少，味美，适合多种烹饪方式',
    cookingMethods: ['清蒸', '红烧', '干煎', '鱼丸'],
    contraindications: '无特殊禁忌',
    baitRecommendation: '嫩草、玉米粒、商品饵（草篇）',
    rigSuggestion: '台钓钓底，玉米粒或商品饵',
    tips: '鳊鱼群居，打窝后容易连竿',
    similarSpecies: ['草鱼', '青鱼'],
    modelLabelId: 12,
  },
  {
    chineseName: '罗非鱼',
    scientificName: 'Oreochromis niloticus',
    family: '丽鱼科',
    genus: '非鲫属',
    aliases: ['非洲鲫', '吴郭鱼', '福寿鱼'],
    habitat: '底层鱼类，适应性强，能在淡水或半咸水中生活，南方广泛养殖',
    diet: '杂食性，以植物性饵料为主，也吃小型水生动物',
    waterLayer: '底层',
    bestSeason: '夏季和初秋（6-10月）',
    protectionLevel: ProtectionLevelEnum.NONE,
    iucnStatus: 'LC',
    edibleRating: '肉质细嫩，刺少，但有土腥味',
    cookingMethods: ['红烧', '烤鱼', '清蒸', '煎炸'],
    contraindications: '有土腥味，处理时可用盐水浸泡',
    baitRecommendation: '商品饵（腥香篇）、蚯蚓、玉米粒',
    rigSuggestion: '台钓钓底，钓饵要雾化慢',
    tips: '罗非鱼吃口猛，漂相清晰，容易上钩',
    similarSpecies: ['太阳鱼', '黑鲷'],
    modelLabelId: 13,
  },
  {
    chineseName: '白条鱼',
    scientificName: 'Hemiculter leucisculus',
    family: '鲤科',
    genus: '白条鱼属',
    aliases: ['窜条', '蓝刀鱼', '小餐鱼'],
    habitat: '上层鱼类，喜集群，活泼好动，主要栖息于溪流和水库的中上层',
    diet: '杂食性，主食浮游动物、水生昆虫、藻类',
    waterLayer: '上层',
    bestSeason: '夏季全天可钓',
    protectionLevel: ProtectionLevelEnum.NONE,
    iucnStatus: 'LC',
    edibleRating: '肉质细嫩，但刺多，适合干炸',
    cookingMethods: ['干炸', '酥鱼', '辣炒'],
    contraindications: '刺多，老人和儿童不宜',
    baitRecommendation: '商品饵（腥香篇）、蚯蚓、飞蝇钩',
    rigSuggestion: '拉饵钓浮，频率要快，线组要细',
    tips: '白条鱼群来时连竿不停，是新手最易上手的鱼种',
    similarSpecies: ['小黄颡', '小参鱼'],
    modelLabelId: 14,
  },
  {
    chineseName: '翘嘴鱼',
    scientificName: 'Culter alburnus',
    family: '鲤科',
    genus: '红鲌属',
    aliases: ['翘嘴红铂', '大白鱼', '翘嘴'],
    habitat: '中上层鱼类，性格凶猛，游速快，主要栖息于水库和湖泊',
    diet: '肉食性，主食小鱼、小虾，也吃水面昆虫',
    waterLayer: '中上层',
    bestSeason: '夏季和秋季（6-11月）',
    protectionLevel: ProtectionLevelEnum.NONE,
    iucnStatus: 'LC',
    edibleRating: '肉质细嫩，刺少，味道鲜美，\"太湖三白\"之一',
    cookingMethods: ['清蒸', '干煎', '生鱼片', '糟鱼'],
    contraindications: '鱼胆不可食用',
    baitRecommendation: '活虾、小鱼、玉米粒、路亚假饵',
    rigSuggestion: '路亚为主，米诺和铅笔效果好，台钓用玉米守钓',
    tips: '翘嘴追饵凶猛，路亚亮片搜索效果最好',
    similarSpecies: ['蒙古红铂', '红眼金鳟'],
    modelLabelId: 15,
  },
  {
    chineseName: '嘎鱼',
    scientificName: 'Pseudobagrus ussuriensis',
    family: '鲿科',
    genus: '黄颡鱼属',
    aliases: ['黄骨鱼', '黄辣丁', '黄辣鱼'],
    habitat: '底层鱼类，喜栖息于乱石、洞穴和水草间，昼伏夜出，全国各地均有分布',
    diet: '肉食性，主食小鱼、小虾、水生昆虫',
    waterLayer: '底层',
    bestSeason: '春季和秋季，夜间是最佳时段',
    protectionLevel: ProtectionLevelEnum.NONE,
    iucnStatus: 'LC',
    edibleRating: '肉质细嫩，刺少，味道极其鲜美，有\"溪鱼之王\"的美誉',
    cookingMethods: ['豆腐鱼汤', '红烧', '香煎', '烤鱼'],
    contraindications: '鱼背有毒刺，处理时注意',
    baitRecommendation: '蚯蚓、红虫、动物肝脏、鸡肠子',
    rigSuggestion: '传统星漂，夜钓守窝，饵料要新鲜',
    tips: '嘎鱼吃饵凶猛，漂相通常是稳稳下顿或黑漂',
    similarSpecies: ['黄鳝', '塘虱'],
    modelLabelId: 16,
  },
  {
    chineseName: '鲶鱼',
    scientificName: 'Silurus asotus',
    family: '鲶科',
    genus: '鲶属',
    aliases: ['土鲶', '鲶拐子', '胡子鱼'],
    habitat: '底层鱼类，适应性强，昼伏夜出，常藏身于水下洞穴和树根下',
    diet: '肉食性，主食小鱼、虾、青蛙，捕食凶猛',
    waterLayer: '底层',
    bestSeason: '夏季和秋季（5-10月）',
    protectionLevel: ProtectionLevelEnum.NONE,
    iucnStatus: 'LC',
    edibleRating: '肉质细嫩，刺少，味道鲜美，但土腥味较重',
    cookingMethods: ['炖汤', '红烧', '垮炖', '烤鱼'],
    contraindications: '鱼卵有毒，不可食用',
    baitRecommendation: '活泥鳅、小鱼、青蛙、鸡肝',
    rigSuggestion: '重铅到底，夜钓守钓，饵料要活',
    tips: '鲶鱼力气大，竿子要结实，线组要粗',
    similarSpecies: ['塘虱', '河鲶'],
    modelLabelId: 17,
  },
  {
    chineseName: '河鲀',
    scientificName: 'Takifugu obscurus',
    family: '鲀科',
    genus: '东方鲀属',
    aliases: ['河豚', '气泡鱼', '嗔鱼'],
    habitat: '底层鱼类，分布于沿海河口和淡水水系，春季溯流产卵',
    diet: '肉食性，主食贝类、小鱼、小虾',
    waterLayer: '底层',
    bestSeason: '春季（3-5月）是河鲀最肥美的季节',
    protectionLevel: ProtectionLevelEnum.NONE,
    iucnStatus: 'EN',
    edibleRating: '肉质极其鲜美，被称为\"鱼中之后\"，但鱼卵和肝脏有毒',
    cookingMethods: ['刺身', '红烧', '白汁'],
    contraindications: '**剧毒**：鱼卵、肝脏、卵巢含河鲀毒素，必须由专业厨师处理',
    baitRecommendation: '螺蛳、贝类、小鱼',
    tips: '部分河鲀为国家保护动物，钓获后建议放生',
    similarSpecies: ['虫纹东方鲀', '假晴河鲀'],
    modelLabelId: 18,
  },
  {
    chineseName: '红眼金鳟',
    scientificName: 'Rhodeus sericeus',
    family: '鲤科',
    genus: '鳜鲋属',
    aliases: ['红眼鱼', '金鳟'],
    habitat: '中层鱼类，喜栖息于水质清澈的溪流和水库',
    diet: '杂食性，以藻类和水生昆虫为主',
    waterLayer: '中层',
    bestSeason: '秋季',
    protectionLevel: ProtectionLevelEnum.NONE,
    iucnStatus: 'LC',
    edibleRating: '肉质细嫩，味美',
    cookingMethods: ['清蒸', '干煎'],
    contraindications: '无特殊禁忌',
    baitRecommendation: '商品饵（腥香篇）、蚯蚓',
    rigSuggestion: '台钓钓中层，轻饵拉',
    tips: '红眼金鳟为中小型鱼，适合休闲垂钓',
    similarSpecies: ['小鳜鱼', '小鲫鱼'],
    modelLabelId: 19,
  },
  {
    chineseName: '中华鲟',
    scientificName: 'Acipenser sinensis',
    family: '鲟科',
    genus: '鲟属',
    aliases: ['鳇鱼', '腊子'],
    habitat: '大型洄游性鱼类，栖息于近海，溯长江而上产卵，是国家一级重点保护动物',
    diet: '肉食性，主食小鱼、小虾和水生昆虫',
    waterLayer: '底层',
    bestSeason: '繁殖期（10-11月）',
    protectionLevel: ProtectionLevelEnum.LEVEL_1,
    iucnStatus: 'CR',
    edibleRating: '**国家一级保护动物，禁止捕杀和食用**',
    cookingMethods: ['禁止食用'],
    contraindications: '**国家一级保护动物，钓获必须立即放生，不得私藏**',
    baitRecommendation: '禁止主动钓捕',
    rigSuggestion: '误捕后立即放生，保护鱼身不受伤害',
    tips: '中华鲟已被列为极危物种，误钓后务必立即放生并拍照记录',
    similarSpecies: ['长江鲟', '施氏鲟'],
    modelLabelId: 20,
  },
];

async function seed() {
  try {
    await dataSource.initialize();
    console.log('Database connected');

    const repo = dataSource.getRepository(FishSpecies);

    // Clear existing data
    await repo.clear();
    console.log('Cleared existing fish species data');

    // Insert new data
    for (const fishData of FISH_SPECIES_DATA) {
      const fish = repo.create(fishData);
      await repo.save(fish);
      console.log(`Seeded: ${fishData.chineseName} (${fishData.scientificName})`);
    }

    console.log(`\nSeeding complete! Total: ${FISH_SPECIES_DATA.length} species`);
  } catch (error) {
    console.error('Seeding failed:', error);
  } finally {
    await dataSource.destroy();
  }
}

seed();