import { DataSource } from 'typeorm';
import { FishSpecies, ProtectionLevelEnum } from '../entities/fish-species.entity';

export async function seedFishSpecies(dataSource: DataSource): Promise<void> {
  const repo = dataSource.getRepository(FishSpecies);

  // Clear existing data
  await repo.clear();

  const speciesData = [
    {
      chineseName: '草鱼',
      scientificName: 'Ctenopharyngodon idella',
      family: '鲤科',
      genus: '草鱼属',
      aliases: ['草鲩', '白鲩', '混子'],
      habitat: '淡水河流湖泊水库水草丰富区',
      diet: '草食性',
      waterLayer: '中下层',
      bestSeason: '春夏秋',
      protectionLevel: ProtectionLevelEnum.NONE,
      edibleRating: '肉质细嫩味美',
      cookingMethods: ['清蒸', '红烧', '糖醋', '炖汤'],
      contraindications: null,
      baitRecommendation: '嫩草玉米红薯菜叶',
      rigSuggestion: '底钓或浮钓子线2-4号主线3-5号',
      tips: '草鱼喜静怕惊',
      similarSpecies: ['青鱼'],
      modelLabelId: null,
      imageUrl: null,
      isActive: true,
    },
    {
      chineseName: '青鱼',
      scientificName: 'Mylopharyngodon piceus',
      family: '鲤科',
      genus: '青鱼属',
      aliases: ['黑鲩', '青鲩', '螺蛳青'],
      habitat: '淡水底层水流缓慢区',
      diet: '肉食性以螺蛳蚌蚬为主',
      waterLayer: '底层',
      bestSeason: '夏秋',
      protectionLevel: ProtectionLevelEnum.NONE,
      edibleRating: '肉质肥美刺少',
      cookingMethods: ['红烧', '清蒸', '腌制'],
      contraindications: null,
      baitRecommendation: '螺蛳蚌肉青蛙颗粒饲料',
      rigSuggestion: '底钓钩大伊势尼8-12号',
      tips: '青鱼力大遛鱼要有耐心',
      similarSpecies: ['草鱼'],
      modelLabelId: null,
      imageUrl: null,
      isActive: true,
    },
    {
      chineseName: '鲢鱼',
      scientificName: 'Hypophthalmichthys molitrix',
      family: '鲤科',
      genus: '鲢属',
      aliases: ['白鲢', '鲢子'],
      habitat: '水体中上层',
      diet: '滤食性浮游生物藻类',
      waterLayer: '中上层',
      bestSeason: '夏',
      protectionLevel: ProtectionLevelEnum.NONE,
      edibleRating: '肉质一般刺多',
      cookingMethods: ['剁椒鱼头', '腌制', '红烧'],
      contraindications: null,
      baitRecommendation: '雾化饵麸皮面粉商品饵',
      rigSuggestion: '浮钓水深1-1.5米子线30-50cm',
      tips: '鲢鱼喜酸臭饵',
      similarSpecies: ['鳙鱼'],
      modelLabelId: null,
      imageUrl: null,
      isActive: true,
    },
    {
      chineseName: '鳙鱼',
      scientificName: 'Aristichthys nobilis',
      family: '鲤科',
      genus: '鳙属',
      aliases: ['花鲢', '胖头鱼', '大头鱼'],
      habitat: '水体中上层',
      diet: '滤食性浮游动物为主',
      waterLayer: '中上层',
      bestSeason: '夏秋',
      protectionLevel: ProtectionLevelEnum.NONE,
      edibleRating: '肉质细嫩特别是鱼头',
      cookingMethods: ['剁椒鱼头', '鱼头汤', '砂锅鱼头'],
      contraindications: null,
      baitRecommendation: '酸臭饵麸皮商品鲢鳙饵',
      rigSuggestion: '浮钓水深1-2米',
      tips: '鳙鱼头特别肥美',
      similarSpecies: ['鲢鱼'],
      modelLabelId: null,
      imageUrl: null,
      isActive: true,
    },
    {
      chineseName: '鲤鱼',
      scientificName: 'Cyprinus carpio',
      family: '鲤科',
      genus: '鲤属',
      aliases: ['鲤子', '拐子', '红鱼'],
      habitat: '淡水底层水草丰富区',
      diet: '杂食性底栖动物植物种子腐屑',
      waterLayer: '底层',
      bestSeason: '春秋冬',
      protectionLevel: ProtectionLevelEnum.NONE,
      edibleRating: '肉质细嫩味美',
      cookingMethods: ['红烧', '糖醋', '清蒸', '鲤鱼焙面'],
      contraindications: null,
      baitRecommendation: '玉米红薯商品饵蚯蚓',
      rigSuggestion: '底钓钩6-10号伊势尼',
      tips: '鲤鱼机警吃饵前有试探',
      similarSpecies: ['鲫鱼'],
      modelLabelId: null,
      imageUrl: null,
      isActive: true,
    },
    {
      chineseName: '鲫鱼',
      scientificName: 'Carassius auratus',
      family: '鲤科',
      genus: '鲫属',
      aliases: ['鲫瓜子', '草鱼子', '月鲫'],
      habitat: '广泛分布池塘河流湖泊',
      diet: '杂食性浮游动物植物种子有机碎屑',
      waterLayer: '底层',
      bestSeason: '全年可钓春季最佳',
      protectionLevel: ProtectionLevelEnum.NONE,
      edibleRating: '肉质细嫩滋补佳品',
      cookingMethods: ['鲫鱼汤', '酥鲫鱼', '红烧鲫鱼'],
      contraindications: null,
      baitRecommendation: '蚯蚓红虫商品饵蓝鲫',
      rigSuggestion: '底钓或悬坠钓钩3-6号袖钩',
      tips: '鲫鱼分布广繁殖快最常见钓鱼对象',
      similarSpecies: ['鲤鱼'],
      modelLabelId: null,
      imageUrl: null,
      isActive: true,
    },
    {
      chineseName: '鳜鱼',
      scientificName: 'Siniperca chuatsi',
      family: '脂科',
      genus: '鳜属',
      aliases: ['桂鱼', '桂花鱼', '季鱼'],
      habitat: '淡水底层岩石缝隙水草区',
      diet: '肉食性小鱼小虾为主',
      waterLayer: '底层',
      bestSeason: '夏秋',
      protectionLevel: ProtectionLevelEnum.NONE,
      edibleRating: '肉质细嫩刺少味极鲜美',
      cookingMethods: ['清蒸鳜鱼', '松鼠桂鱼', '红烧鳜鱼'],
      contraindications: null,
      baitRecommendation: '小鱼泥鳅亮片软虫',
      rigSuggestion: '路亚或手竿钩要锋利',
      tips: '鳜鱼伏击捕食钓时安静',
      similarSpecies: ['罗非鱼'],
      modelLabelId: null,
      imageUrl: null,
      isActive: true,
    },
    {
      chineseName: '黑鱼',
      scientificName: 'Channa argus',
      family: '鳢科',
      genus: '鳢属',
      aliases: ['乌鳢', '生鱼', '财鱼'],
      habitat: '淡水底层水草密集静水或缓流',
      diet: '肉食性小鱼青蛙泥鳅',
      waterLayer: '中下层',
      bestSeason: '夏秋',
      protectionLevel: ProtectionLevelEnum.NONE,
      edibleRating: '肉质紧实味道鲜美',
      cookingMethods: ['水煮黑鱼', '酸菜鱼', '黑鱼汤'],
      contraindications: null,
      baitRecommendation: '小鱼泥鳅青蛙路亚饵',
      rigSuggestion: '路亚或手竿重窝钓底',
      tips: '黑鱼凶猛逃跑力量大',
      similarSpecies: ['鳜鱼'],
      modelLabelId: null,
      imageUrl: null,
      isActive: true,
    },
    {
      chineseName: '鲈鱼',
      scientificName: 'Lateolabrax japonicus',
      family: '鲈科',
      genus: '花鲈属',
      aliases: ['花鲈', '七星鲈', '大口黑鲈'],
      habitat: '沿海咸淡水交界处也进入淡水',
      diet: '肉食性小鱼虾软体动物',
      waterLayer: '中层',
      bestSeason: '秋冬',
      protectionLevel: ProtectionLevelEnum.NONE,
      edibleRating: '肉质白嫩刺少味美',
      cookingMethods: ['清蒸鲈鱼', '红烧鲈鱼', '烤鲈鱼'],
      contraindications: null,
      baitRecommendation: '小鱼虾软虫路亚饵',
      rigSuggestion: '路亚或海竿钩要锋利',
      tips: '鲈鱼对水质要求高',
      similarSpecies: ['鳜鱼'],
      modelLabelId: null,
      imageUrl: null,
      isActive: true,
    },
    {
      chineseName: '鳊鱼',
      scientificName: 'Parabramis pekinensis',
      family: '鲤科',
      genus: '鳊属',
      aliases: ['长春鳊', '北京鳊'],
      habitat: '淡水中下层水草丰富的缓流',
      diet: '草食性水草植物种子',
      waterLayer: '中下层',
      bestSeason: '春秋',
      protectionLevel: ProtectionLevelEnum.NONE,
      edibleRating: '肉质细嫩',
      cookingMethods: ['清蒸鳊鱼', '红烧鳊鱼', '干煎'],
      contraindications: null,
      baitRecommendation: '嫩草玉米商品饵',
      rigSuggestion: '底钓或浮钓',
      tips: '鳊鱼集群觅食',
      similarSpecies: ['草鱼'],
      modelLabelId: null,
      imageUrl: null,
      isActive: true,
    },
    {
      chineseName: '罗非鱼',
      scientificName: 'Oreochromis niloticus',
      family: '丽鱼科',
      genus: '非鲫属',
      aliases: ['非洲鲫', '吴郭鱼', '福寿鱼'],
      habitat: '热带淡水水体中下层',
      diet: '杂食性藻类浮游动物水蚯蚓',
      waterLayer: '中下层',
      bestSeason: '夏秋',
      protectionLevel: ProtectionLevelEnum.NONE,
      edibleRating: '肉质细嫩刺少',
      cookingMethods: ['红烧罗非', '清蒸罗非', '烤罗非'],
      contraindications: null,
      baitRecommendation: '商品饵蚯蚓虾仁面包屑',
      rigSuggestion: '手竿底钓钩4-8号袖',
      tips: '罗非鱼繁殖快适应能力强',
      similarSpecies: ['鳜鱼'],
      modelLabelId: null,
      imageUrl: null,
      isActive: true,
    },
    {
      chineseName: '黄鳝',
      scientificName: 'Monopterus albus',
      family: '合鳃鱼科',
      genus: '黄鳝属',
      aliases: ['鳝鱼', '长鱼'],
      habitat: '淡水底层稻田沼泽池塘',
      diet: '肉食性小鱼虾昆虫幼虫',
      waterLayer: '底层',
      bestSeason: '夏秋夜钓最佳',
      protectionLevel: ProtectionLevelEnum.NONE,
      edibleRating: '肉质细嫩营养丰富',
      cookingMethods: ['爆炒黄鳝', '黄鳝粥', '黄鳝汤', '红烧黄鳝'],
      contraindications: null,
      baitRecommendation: '蚯蚓小鱼虾',
      rigSuggestion: '竹竿钓或竖漂钓钩要大',
      tips: '黄鳝夜行性夜钓效果更好',
      similarSpecies: ['泥鳅'],
      modelLabelId: null,
      imageUrl: null,
      isActive: true,
    },
    {
      chineseName: '泥鳅',
      scientificName: 'Misgurnus anguillicaudatus',
      family: '鳅科',
      genus: '泥鳅属',
      aliases: ['鱼鳅', '土鳅'],
      habitat: '淡水底层淤泥丰富的水域',
      diet: '杂食性腐屑藻类浮游动物',
      waterLayer: '底层',
      bestSeason: '春夏秋',
      protectionLevel: ProtectionLevelEnum.NONE,
      edibleRating: '营养丰富称为水中人参',
      cookingMethods: ['泥鳅钻豆腐', '干煸泥鳅', '炸泥鳅', '泥鳅汤'],
      contraindications: null,
      baitRecommendation: '蚯蚓商品饵面粉团',
      rigSuggestion: '散漂钓底钩要小',
      tips: '泥鳅耐低氧适应性强',
      similarSpecies: ['黄鳝'],
      modelLabelId: null,
      imageUrl: null,
      isActive: true,
    },
    {
      chineseName: '鲇鱼',
      scientificName: 'Silurus asotus',
      family: '鲇科',
      genus: '鲇属',
      aliases: ['鲶鱼', '土鲇', '年鱼'],
      habitat: '淡水底层岩石缝隙洞穴',
      diet: '肉食性小鱼虾青蛙',
      waterLayer: '底层',
      bestSeason: '夏秋',
      protectionLevel: ProtectionLevelEnum.NONE,
      edibleRating: '肉质细嫩刺少',
      cookingMethods: ['鲇鱼炖豆腐', '红烧鲇鱼', '清蒸鲇鱼'],
      contraindications: null,
      baitRecommendation: '小鱼蚯蚓鸡肝青蛙',
      rigSuggestion: '手竿或海竿重坠底钓',
      tips: '鲇鱼夜行性夜钓效果更好',
      similarSpecies: ['黑鱼'],
      modelLabelId: null,
      imageUrl: null,
      isActive: true,
    },
    {
      chineseName: '翘嘴',
      scientificName: 'Culter alburnus',
      family: '鲤科',
      genus: '红鲌属',
      aliases: ['蒙古红鲌', '翘嘴红鲌', '大白鱼'],
      habitat: '淡水敞水区中上层',
      diet: '肉食性小鱼虾',
      waterLayer: '中上层',
      bestSeason: '夏秋',
      protectionLevel: ProtectionLevelEnum.NONE,
      edibleRating: '肉质细嫩味道鲜美',
      cookingMethods: ['清蒸翘嘴', '干烧翘嘴', '腌制'],
      contraindications: null,
      baitRecommendation: '小鱼虾泥鳅路亚饵',
      rigSuggestion: '浮钓或路亚钩要锋利',
      tips: '翘嘴追逐小鱼炸水声可判断位置',
      similarSpecies: ['红眼鱼'],
      modelLabelId: null,
      imageUrl: null,
      isActive: true,
    },
    {
      chineseName: '太阳鱼',
      scientificName: 'Lepomis macrochirus',
      family: '棘臀鱼科',
      genus: '太阳鱼属',
      aliases: ['蓝鳃太阳鱼'],
      habitat: '淡水水草丰富的静水或缓流',
      diet: '杂食性浮游动物昆虫小鱼',
      waterLayer: '中下层',
      bestSeason: '春夏秋',
      protectionLevel: ProtectionLevelEnum.NONE,
      edibleRating: '肉质细嫩',
      cookingMethods: ['清蒸', '红烧', '烧烤'],
      contraindications: null,
      baitRecommendation: '蚯蚓红虫商品饵',
      rigSuggestion: '手竿轻坠钩3-6号袖',
      tips: '太阳鱼个体小群体觅食',
      similarSpecies: ['罗非鱼'],
      modelLabelId: null,
      imageUrl: null,
      isActive: true,
    },
    {
      chineseName: '虹鳟',
      scientificName: 'Oncorhynchus mykiss',
      family: '鲑科',
      genus: '太平洋虹鳟属',
      aliases: ['虹鳟鱼', '三文鳟'],
      habitat: '冷水淡水山区溪流水库',
      diet: '肉食性小鱼昆虫软体动物',
      waterLayer: '中下层',
      bestSeason: '春秋冬',
      protectionLevel: ProtectionLevelEnum.NONE,
      edibleRating: '肉质橙红色味美',
      cookingMethods: ['刺身', '烟熏', '香煎', '清蒸'],
      contraindications: null,
      baitRecommendation: '人工蝇饵蚯蚓小鱼',
      rigSuggestion: '飞蝇钓或路亚水质清澈',
      tips: '虹鳟对水质要求高需要冷水环境',
      similarSpecies: ['金鳟'],
      modelLabelId: null,
      imageUrl: null,
      isActive: true,
    },
    {
      chineseName: '金鳟',
      scientificName: 'Oncorhynchus mykiss var.',
      family: '鲑科',
      genus: '太平洋虹鳟属',
      aliases: ['金鳟鱼', '虹鳟变种'],
      habitat: '冷水淡水山区溪流',
      diet: '肉食性小鱼昆虫',
      waterLayer: '中下层',
      bestSeason: '春秋冬',
      protectionLevel: ProtectionLevelEnum.NONE,
      edibleRating: '肉质金黄色美观味美',
      cookingMethods: ['刺身', '清蒸', '红烧'],
      contraindications: null,
      baitRecommendation: '人工蝇饵蚯蚓小鱼',
      rigSuggestion: '飞蝇钓或路亚',
      tips: '金鳟是虹鳟的变种',
      similarSpecies: ['虹鳟'],
      modelLabelId: null,
      imageUrl: null,
      isActive: true,
    },
    {
      chineseName: '中华鲟',
      scientificName: 'Acipenser sinensis',
      family: '鲟科',
      genus: '鲟属',
      aliases: ['鲟鱼', '鳣鱼', '黄鲟'],
      habitat: '长江流域底层',
      diet: '肉食性小鱼虾软体动物',
      waterLayer: '底层',
      bestSeason: '秋',
      protectionLevel: ProtectionLevelEnum.LEVEL_1,
      edibleRating: '珍贵保护动物禁止捕食',
      cookingMethods: ['禁止食用'],
      contraindications: '国家一级保护动物，禁止捕食',
      baitRecommendation: '不适合钓鱼保护动物',
      rigSuggestion: '保护动物禁止垂钓',
      tips: '中华鲟是国家一级保护动物钓获应立即放生',
      similarSpecies: ['长江鲟', '达氏鲟'],
      modelLabelId: null,
      imageUrl: null,
      isActive: true,
    },
    {
      chineseName: '河鲀',
      scientificName: 'Takifugu obscurus',
      family: '鲀科',
      genus: '东方鲀属',
      aliases: ['河豚', '气泡鱼', '气鼓鱼'],
      habitat: '淡水及咸淡水底层',
      diet: '肉食性小鱼虾贝类',
      waterLayer: '底层',
      bestSeason: '春秋',
      protectionLevel: ProtectionLevelEnum.NONE,
      edibleRating: '鲜美至极但内脏有毒需专业处理',
      cookingMethods: ['河鲀刺身', '红烧河鲀', '河鲀汤'],
      contraindications: '河鲀内脏有毒，处理需专业人员',
      baitRecommendation: '小鱼虾贝肉',
      rigSuggestion: '竿钓或手线钩中号',
      tips: '河鲀有毒腺处理需专业人员',
      similarSpecies: ['暗纹东方鲀'],
      modelLabelId: null,
      imageUrl: null,
      isActive: true,
    },
  ];

  const entities = repo.create(speciesData);
  await repo.save(entities);

  console.log(`Seeded ${entities.length} fish species`);
}